# 0.0 - Imports and Load

In [1]:
import pandas as pd 

from pysus import SIA

## 0.1 - Load Dataset

In [2]:
sia = SIA().load()

In [ ]:
years = [ 2019, 2020, 2021]
files = sia.get_files('BI', uf = 'PB', year= years)

In [18]:
len(files)

36

## 1.0 - Metadados

In [10]:
sia.describe(files[0])

{'name': 'BIPB1901.dbc',
 'group': 'Boletim de Produção Ambulatorial individualizado',
 'uf': 'Paraíba',
 'month': 'Janeiro',
 'year': 2019,
 'size': '14.3 MB',
 'last_update': '2020-04-16 07:52PM'}

In [ ]:
metadata = []

for f in files:
    describe = sia.describe(f)
    metadata.append(describe)


df_meta = pd.DataFrame(metadata)

In [21]:
df_meta

,name,group,uf,month,year,size,last_update
0,PAPB1901.dbc,Produção Ambulatorial,Paraíba,Janeiro,2019,15.8 MB,2020-04-16 07:54PM
1,PAPB1902.dbc,Produção Ambulatorial,Paraíba,Fevereiro,2019,15.9 MB,2020-04-16 07:54PM
2,PAPB1903.dbc,Produção Ambulatorial,Paraíba,Março,2019,17.5 MB,2020-07-06 02:15PM
3,PAPB1904.dbc,Produção Ambulatorial,Paraíba,Abril,2019,18.9 MB,2020-07-06 02:15PM
4,PAPB1905.dbc,Produção Ambulatorial,Paraíba,Maio,2019,19.8 MB,2020-07-06 02:15PM
5,PAPB1906.dbc,Produção Ambulatorial,Paraíba,Junho,2019,19.6 MB,2020-09-04 06:00PM
6,PAPB1907.dbc,Produção Ambulatorial,Paraíba,Julho,2019,24.7 MB,2020-10-08 03:58PM
7,PAPB1908.dbc,Produção Ambulatorial,Paraíba,Agosto,2019,24.0 MB,2020-10-08 03:58PM
8,PAPB1909.dbc,Produção Ambulatorial,Paraíba,Setembro,2019,23.2 MB,2020-12-10 06:04AM
9,PAPB1910.dbc,Produção Ambulatorial,Paraíba,Outubro,2019,21.3 MB,2020-12-10 06:04AM
10,PAPB1911.dbc,Produção Ambulatorial,Paraíba,Novembro,2019,20.0 MB,2021-01-13 08:31PM
11,PAPB1912.dbc,Produção Ambulatorial,Paraíba,Dezembro,2019,17.8 MB,2021-02-05 06:11PM
12,PAPB2001.dbc,Produção Ambulatorial,Paraíba,Janeiro,2020,17.0 MB,2021-04-05 08:35PM
13,PAPB2002.dbc,Produção Ambulatorial,Paraíba,Fevereiro,2020,18.5 MB,2021-04-05 08:35PM
14,PAPB2003.dbc,Produção Ambulatorial,Paraíba,Março,2020,14.6 MB,2021-06-07 12:41PM
15,PAPB2004.dbc,Produção Ambulatorial,Paraíba,Abril,2020,7.6 MB,2021-07-05 07:31PM
16,PAPB2005.dbc,Produção Ambulatorial,Paraíba,Maio,2020,7.4 MB,2021-07-05 07:31PM
17,PAPB2006.dbc,Produção Ambulatorial,Paraíba,Junho,2020,8.8 MB,2021-08-05 12:09AM
18,PAPB2007.dbc,Produção Ambulatorial,Paraíba,Julho,2020,11.3 MB,2021-09-06 04:26AM
19,PAPB2008.dbc,Produção Ambulatorial,Paraíba,Agosto,2020,12.7 MB,2021-09-06 04:26AM
20,PAPB2009.dbc,Produção Ambulatorial,Paraíba,Setembro,2020,13.9 MB,2021-10-08 07:08PM
21,PAPB2010.dbc,Produção Ambulatorial,Paraíba,Outubro,2020,18.5 MB,2021-11-05 08:39PM
22,PAPB2011.dbc,Produção Ambulatorial,Paraíba,Novembro,2020,17.8 MB,2021-12-07 11:50AM
23,PAPB2012.dbc,Produção Ambulatorial,Paraíba,Dezembro,2020,14.8 MB,2022-01-07 06:47AM
24,PAPB2101.dbc,Produção Ambulatorial,Paraíba,Janeiro,2021,14.0 MB,2023-10-12 03:03PM
25,PAPB2102.dbc,Produção Ambulatorial,Paraíba,Fevereiro,2021,16.5 MB,2023-10-12 03:04PM
26,PAPB2103.dbc,Produção Ambulatorial,Paraíba,Março,2021,15.0 MB,2023-10-12 03:04PM
27,PAPB2104.dbc,Produção Ambulatorial,Paraíba,Abril,2021,15.1 MB,2023-10-12 03:04PM
28,PAPB2105.dbc,Produção Ambulatorial,Paraíba,Maio,2021,17.3 MB,2023-10-12 03:04PM
29,PAPB2106.dbc,Produção Ambulatorial,Paraíba,Junho,2021,17.9 MB,2023-10-12 03:04PM
30,PAPB2107.dbc,Produção Ambulatorial,Paraíba,Julho,2021,19.9 MB,2023-10-12 03:04PM
31,PAPB2108.dbc,Produção Ambulatorial,Paraíba,Agosto,2021,20.4 MB,2023-10-12 03:04PM
32,PAPB2109.dbc,Produção Ambulatorial,Paraíba,Setembro,2021,19.1 MB,2023-10-12 03:04PM
33,PAPB2110.dbc,Produção Ambulatorial,Paraíba,Outubro,2021,20.6 MB,2023-10-12 03:04PM
34,PAPB2111.dbc,Produção Ambulatorial,Paraíba,Novembro,2021,19.7 MB,2023-10-12 03:04PM
35,PAPB2112.dbc,Produção Ambulatorial,Paraíba,Dezembro,2021,15.7 MB,2023-10-12 03:04PM

In [13]:
df_meta["month"].value_counts()

month
Janeiro      3
Fevereiro    3
Março        3
Abril        3
Maio         3
Junho        3
Julho        3
Agosto       3
Setembro     3
Outubro      3
Novembro     3
Dezembro     3
Name: count, dtype: int64

In [14]:
df_meta["year"].value_counts()

year
2019    12
2020    12
2021    12
Name: count, dtype: int64

In [16]:
df_meta.groupby("year")["size"].sum()

year
2019    14.3 MB14.6 MB16.9 MB18.5 MB19.5 MB18.4 MB21.1...
2020    15.6 MB15.7 MB12.3 MB5.4 MB5.8 MB7.2 MB9.7 MB1...
2021    11.9 MB13.3 MB13.3 MB13.3 MB15.6 MB15.9 MB18.2...
Name: size, dtype: object

# 2.0 -Reading Data

In [19]:
dfs = []
for f in files:
    parquet = sia.download(f)
    print(f"download concluindo do arquvio {f}")
    df = parquet.to_dataframe()
    dfs.append(df)

15784570it [00:00, 1396765439.97it/s]

download concluindo do arquvio PAPB1901.dbc

15929092it [00:00, 4282511011.60it/s]

download concluindo do arquvio PAPB1902.dbc

17494374it [00:00, 5768156815.16it/s]

download concluindo do arquvio PAPB1903.dbc

18943782it [00:00, 3654660807.59it/s]

download concluindo do arquvio PAPB1904.dbc

19807010it [00:00, 2175293165.17it/s]

download concluindo do arquvio PAPB1905.dbc

19638044it [00:00, 2469876952.87it/s]

download concluindo do arquvio PAPB1906.dbc

24653932it [00:00, 9155031925.93it/s]

download concluindo do arquvio PAPB1907.dbc

PAPB1908.parquet: 100%|██████████| 1.30M/1.30M [00:39<00:00, 33.3kB/s]

download concluindo do arquvio PAPB1908.dbc

PAPB1909.parquet:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

KeyboardInterrupt:

PAPB1909.parquet:   7%|▋         | 90.0k/1.27M [00:16<03:30, 5.61kB/s]

In [8]:
df_final = pd.concat(dfs, ignore_index=True)

In [9]:
df_final

,CODUNI,GESTAO,CONDIC,UFMUN,TPUPS,TIPPRE,MN_IND,CNPJCPF,CNPJMNT,CNPJ_CC,...,RACACOR,MUNPAC,QT_APRES,QT_APROV,VL_APRES,VL_APROV,UFDIF,MNDIF,ETNIA,NAT_JUR
0,7927908,250180,PG,250180,73,00,M,08924581000160,08924581000160,00000000000000,...,03,250180,1,1,0.63,0.63,0,0,,1244
1,2605430,250010,PG,250010,15,00,M,09145368000112,09145368000112,00000000000000,...,01,250010,1,1,45.00,45.00,0,0,,1244
2,2363879,250380,PG,250380,01,00,M,08809071000141,08809071000141,00000000000000,...,01,250380,1,1,150.00,150.00,0,0,,1244
3,5860431,251230,PG,251230,36,00,M,08888968000108,08888968000108,00000000000000,...,03,251230,1,1,0.00,0.00,0,0,,1244
4,6438407,251230,PG,251230,81,00,M,08888968000108,08888968000108,00000000000000,...,03,251230,16,16,79.20,79.20,0,0,,1244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10868110,2593262,250000,EP,250750,05,00,M,08778268003771,08778268000160,00000000000000,...,99,250750,1,1,101.10,101.10,0,0,,1023
10868111,2593262,250000,EP,250750,05,00,M,08778268003771,08778268000160,00000000000000,...,02,250750,1,1,97.44,97.44,0,0,,1023
10868112,2605473,250000,EP,251080,05,00,M,08778268002376,08778268000160,00000000000000,...,03,251130,1,1,97.44,97.44,0,1,,1023
10868113,2605473,250000,EP,251080,05,00,M,08778268002376,08778268000160,00000000000000,...,03,354880,1,1,97.44,97.44,1,1,,1023
10868114,2757761,250000,EP,250750,36,00,M,08778268004409,08778268000160,00000000000000,...,03,250750,1,1,10.00,10.00,0,0,,1023

# 3.0 - EDA